[features]
seeds = false
skip-lint = false
[programs.localnet]
decapsule = "4vYgtqYrVNfRX8nXePm8XjUhaCuWpqmC2c2HJtU5LVff"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/suyashgupte/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
