[features]
seeds = false
skip-lint = false
[programs.localnet]
decapsule = "6dJGf3EYNT3g8Qj9vXTxdVjzTGCs9udYu4cTRCEMGL9J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/suyashgupte/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
